// <auto-generated />
namespace C4W.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventsInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventsInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201606150438091_eventsInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
